### PR TITLE
Locally sourced internet: vendor the bootstrap source into Git

### PR DESCRIPTION
**Pull request by altf4arnold**
Saw while loading the incubator on a slow internet connection that bootstrap timed out. Started to relocate bootstrap. Seems to work. I think we can relocate fontawesome (maybe google font to?)

I didn't understood how fontawesome worked. So not yet done.

### CODE REVIEW

**Comment by C4ptainCrunch** [comment]
I have mixed feelings about this PR. While **it's nice to not have to rely on CDNs :+1: ** (and their most likely tracking) i do not like that fact that we copy the files to be served into our repo.

This, for multiple reasons:
* What about the license, do we have the right to copy those files ? And the copyright notice ?
* It commits many KB (or MB) of source in Git, that is not designed to handle big commits well
* Once we put it in master, even if we remove it, it there forever, there is no way back
* (It breaks the commit stats, there will be thousands of + and -)

I'm guessing that these problems have already been solved by somebody else, probably by downloading those at build/collectstatic time ? Could you have a look at the solutions that exist ?
If we find one, we also should be careful about the added complexity (more things that can break) and the dev friendliness (we don't want one more tool with one more command that we have to run each time we want to ./manage.py run for example)

**Comment by altf4arnold** [comment]
> I have mixed feelings about this PR. While **it's nice to not have to rely on CDNs** 👍 (and their most likely tracking) i do not like that fact that we copy the files to be served into our repo.
> 
> This, for multiple reasons:
> 
>     * What about the license, do we have the right to copy those files ? And the copyright notice ?
> 
>     * It commits many KB (or MB) of source in Git, that is not designed to handle big commits well
> 
>     * Once we put it in master, even if we remove it, it there forever, there is no way back
> 
>     * (It breaks the commit stats, there will be thousands of + and -)
> 
> 
> I'm guessing that these problems have already been solved by somebody else, probably by downloading those at build/collectstatic time ? Could you have a look at the solutions that exist ? If we find one, we also should be careful about the added complexity (more things that can break) and the dev friendliness (we don't want one more tool with one more command that we have to run each time we want to ./manage.py run for example)
> 
> Edit: if you still decide to follow the vendor/"copy into git" path, could you have a look and remove the obsolete libraries ? (at least https://github.com/UrLab/incubator/blob/main/incubator/settings.py#L58 i guess)

Will investigate further on another way. Found stuff

**Comment by titouanc** [comment]
@C4ptainCrunch  Not sure of what you meant with 

> Once we put it in master, even if we remove it, it there forever, there is no way back

I tend to agree with your comments, maybe another way would be simply to have a script committed in this repo that downloads the static files and install them as needed, so we have a reproducible way to get them (and we simply have to change the version number in this script to update Bootstrap)

@altf4arnold Also we don't need both the `.js/.css` and the `.min` versions of the same files :wink:

**Comment by altf4arnold** [comment]
I still have some doc to read to see if we can do with bootstrap 4 what could be done with this previously https://pypi.org/project/django-bootstrap-static/ so we don't have to get all the files manually. 

Regarding the fact that we can't host the files ourself, I didn't found anything on the site of bootstrap. They seem to suggest that we can host them ourself without specifying anything...

**Comment by C4ptainCrunch** [comment]
> @C4ptainCrunch Not sure of what you meant with
> > Once we put it in master, even if we remove it, it there forever, there is no way back

I meant that the files are in the repo forever, because of the immutability of git

**Comment by Mortinat** [comment]
> @C4ptainCrunch I meant that the files are in the repo forever, because of the immutability of git
Not totally true we can still overwrite the history of the commit not great but it works https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

**Comment by KodiCraft** [comment]
That should most definitely be avoided on a public repository.

If we need to mirror files, we most definitely need a static bucket and at least a bit of a CDN, these should not be in the source code. This could be done with something like a Cloudflare bucket but at that point there isn't much difference from just getting the files from bootstrap.

**Pull request closed without merging**
