### PR TITLE
update of the event page

### PR DESCRIPTION
**Pull request by melcar**
refactored it to make it look like the project page.
Like that we'll be able to see all the past project and not just a subsequence of them. that way it'll be eeasier to access all the ressources from the old smartmondays and stuff like that

### CODE REVIEW

**Comment by C4ptainCrunch** [comment]
screenshot or fake !

**Comment by melcar** [comment]
@C4ptainCrunch nothing crazy
image
like project but for events. next step : add catagories to even to do some filtering and search on them
image
image

**Comment by melcar** [comment]
voila j'ai ajouté du wordwrap la ou c'était nécéssaire
image
image
image

**Comment by PierreGe** [comment]
Selection_999(078)

I love how the totally random glyphicons I choose 4 years ago are still there :smile:

**Comment by melcar** [comment]
@PierreGe if it ain't broke don't change it

**Pull request merged**
