### PR TITLE
Interdiction des images en http dans les fields de markdown

### LINKED ISSUE #157: Interdire le http dans markdown
Il est actuellement possible d'inclure des images en http dans l'éditeur de projet/event/(...).
Ça provoque des warnings dans le navigateur parce que le site est en https.

TODO: procéder à une vérification des liens pour interdire l'inclusion d'images http.

### PR DESCRIPTION
**Pull request by Minigrim0**
Non https images are not allowed in the project creation/edit form :
image

in the comments of the projects
image

And in the wiki articles
image

Closes #157

### CODE REVIEW

**Comment by altf4arnold** [comment]
Given that this will not prevent HTTPS from breaking when certificates are not renewed, is this really needed? Maybe encouraging to use locally hosted stuff would be better?

**Comment by thibault-v** [comment]
> Given that this will not prevent HTTPS from breaking when certificates are not renewed, is this really needed?
I do not see any link between the current issue and certificates renewing.

> Maybe encouraging to use locally hosted stuff would be better?
As we are not providing any way for users to locally host images, this is not relevant.

**Comment by thibault-v** [comment]
@Minigrim0 I think you are missing the text editor of the events section :D

**Comment by Minigrim0** [comment]
@thibault-v fixed :)
image

**Pull request merged**
